/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["UsersController_search"];
  };
  "/users/@me": {
    get: operations["UsersController_getMyself"];
  };
  "/users/@me/activity-feed": {
    get: operations["UsersController_getMyActivityFeed"];
  };
  "/users/@me/queue/{journey_id}": {
    put: operations["UsersController_addJourneyToMyQueue"];
    delete: operations["UsersController_removeJourneyFromMyQueue"];
  };
  "/users/@me/queue": {
    get: operations["UsersController_getMyQueue"];
  };
  "/users/{id}": {
    get: operations["UsersController_getOneById"];
    patch: operations["UsersController_updateOneById"];
  };
  "/users/{id}/activity": {
    get: operations["UsersController_getUserActivity"];
  };
  "/journeys": {
    get: operations["JourneysController_findAll"];
    post: operations["JourneysController_createOne"];
  };
  "/journeys/{id}": {
    get: operations["JourneysController_findOneById"];
  };
  "/auth/osu": {
    get: operations["AuthController_osuLogin"];
  };
  "/auth/osu/callback": {
    get: operations["AuthController_osuLoginCallback"];
  };
}

export interface components {
  schemas: {
    UserData: {
      /** User's unique id */
      id: number;
      /** User's osu id */
      osu_id: number;
      name: string;
      avatar_url: string;
      banner_url: string;
      description: string;
    };
    CoverData: {
      banner: string;
      thumbnail: string;
    };
    JourneyData: {
      /** Journeys unique id */
      id: number;
      /** Osu's unique id */
      osu_id: number;
      title: string;
      artist: string;
      osu_link: string;
      organizer: components["schemas"]["UserData"];
      covers: components["schemas"]["CoverData"];
    };
    ActivityData: {
      id: number;
      created_at: string;
      kind: "userAddedJourneyToQueue" | "userRemovedJourneyFromQueue";
      user: components["schemas"]["UserData"] | null;
      journey: components["schemas"]["JourneyData"] | null;
    };
    UserUpdateInput: {
      name: string;
      avatar_url: string | null;
      banner_url: string | null;
      email: string | null;
      is_available: boolean | null;
      description: string | null;
    };
    JourneyCreateInput: {
      osu_link: string;
    };
    AuthPayload: {
      token_type: string;
      access_token: string;
      expires_in: number;
    };
  };
}

export interface operations {
  UsersController_search: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserData"][];
        };
      };
    };
  };
  UsersController_getMyself: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserData"];
        };
      };
    };
  };
  UsersController_getMyActivityFeed: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ActivityData"][];
        };
      };
    };
  };
  UsersController_addJourneyToMyQueue: {
    parameters: {
      path: {
        journey_id: number;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UsersController_removeJourneyFromMyQueue: {
    parameters: {
      path: {
        journey_id: number;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UsersController_getMyQueue: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JourneyData"][];
        };
      };
    };
  };
  UsersController_getOneById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserData"];
        };
      };
      404: unknown;
    };
  };
  UsersController_updateOneById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserData"];
        };
      };
      401: unknown;
      404: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateInput"];
      };
    };
  };
  UsersController_getUserActivity: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ActivityData"][];
        };
      };
    };
  };
  JourneysController_findAll: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JourneyData"];
        };
      };
    };
  };
  JourneysController_createOne: {
    parameters: {};
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["JourneyData"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JourneyCreateInput"];
      };
    };
  };
  JourneysController_findOneById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JourneyData"];
        };
      };
    };
  };
  AuthController_osuLogin: {
    parameters: {};
    responses: {
      307: never;
    };
  };
  AuthController_osuLoginCallback: {
    parameters: {
      query: {
        code: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AuthPayload"];
        };
      };
    };
  };
}
